basePath: /api/v1
definitions:
  forms.Blog:
    properties:
      author:
        default: admin
        type: string
      title:
        type: string
    type: object
host: localhost:7000
info:
  contact: {}
  description: Blog Service API in Go using GIN framework
  title: Blog Service API
  version: "1.0"
paths:
  /blog:
    get:
      description: Return list of blog.
      responses: {}
      summary: Get Blogs.
      tags:
      - Blog
    post:
      description: Return blog data.
      parameters:
      - description: Request body for creating a resource
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/forms.Blog'
      responses: {}
      summary: Create Blogs.
      tags:
      - Blog
  /blog/{id}:
    delete:
      description: Return no context status.
      parameters:
      - description: ID of models.Blog
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: Delete Blogs.
      tags:
      - Blog
    put:
      description: Return new blog after update data.
      parameters:
      - description: ID of models.Blog
        in: path
        name: id
        required: true
        type: integer
      - description: Request body for update a resource
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/forms.Blog'
      responses: {}
      summary: Update Blogs.
      tags:
      - Blog
swagger: "2.0"
